"""empty message

Revision ID: e5e6762a965b
Revises: 3710ac02a009
Create Date: 2022-03-17 23:03:47.952389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e6762a965b'
down_revision = '3710ac02a009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('contact', sa.Column('user_token', sa.String(), nullable=False))
    op.drop_constraint('contact_user_taken_fkey', 'contact', type_='foreignkey')
    op.create_foreign_key(None, 'contact', 'user', ['user_token'], ['token'])
    op.drop_column('contact', 'user_taken')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('user_taken', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.create_foreign_key('contact_user_taken_fkey', 'contact', 'user', ['user_taken'], ['token'])
    op.drop_column('contact', 'user_token')
    op.drop_column('contact', 'phone_number')
    # ### end Alembic commands ###
